### ISSUE TITLE
test

### ISSUE THREAD

**Issue by vae520283995** [vae520283995/simple#1]
`SAS:
📦 LOG:
✅ LEVEL: "info"
✅ JSON: false
✅ FILTER_RPC: false
✅ STRIP_ANSI: false
📦 SUBSTRATE:
✅ WS_URL: "ws://127.0.0.1:19966"
✅ TYPES_BUNDLE: undefined
✅ TYPES_CHAIN: undefined
✅ TYPES_SPEC: undefined
✅ TYPES: undefined
📦 EXPRESS:
✅ BIND_HOST: "0.0.0.0"
✅ PORT: 8080
2021-05-16 03:47:18 info: Version: 6.0.0
2021-05-16 03:47:20 info: Connected to chain Kusama on the parity-kusama client at ws://127.0.0.1:19966
2021-05-16 03:47:20 warn: Using unencrypted connection to a public node (ws://127.0.0.1:19966); All traffic is sent over the internet in cleartext.
2021-05-16 03:47:20 info: Listening on http://0.0.0.0:8080/
2021-05-16 03:47:20 info: Check the root endpoint (http://0.0.0.0:8080/) to see the available endpoints for the current node
2021-05-16 03:47:25 error: VEC: Unable to decode on index 2 createType(ExtrinsicV4):: createType(Call):: Call: failed decoding electionProviderMultiPhase.submitUnsigned:: Struct: failed on args: {"solution":"RawSolution","witness":"SolutionOrSnapshotSize"}:: u32: Input too large. Found input with 77 bits, expected 32
2021-05-16 03:47:25 error: RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec"}:: Struct: failed on extrinsics: Vec:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding electionProviderMultiPhase.submitUnsigned:: Struct: failed on args: {"solution":"RawSolution","witness":"SolutionOrSnapshotSize"}:: u32: Input too large. Found input with 77 bits, expected 32
2021-05-16 03:47:28 error: VEC: Unable to decode on index 2 createType(ExtrinsicV4):: createType(Call):: Call: failed decoding electionProviderMultiPhase.submitUnsigned:: Struct: failed on args: {"solution":"RawSolution","witness":"SolutionOrSnapshotSize"}:: u32: Input too large. Found input with 77 bits, expected 32
2021-05-16 03:47:28 error: RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec"}:: Struct: failed on extrinsics: Vec:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding electionProviderMultiPhase.submitUnsigned:: Struct: failed on args: {"solution":"RawSolution","witness":"SolutionOrSnapshotSize"}:: u32: Input too large. Found input with 77 bits, expected 32 `

**Comment by vae520283995** [comment]
`const api = await ApiPromise.create({
		provider: new WsProvider('wss://kusama.api.onfinality.io/public-ws'),
	});

	const blockHash7487667 = await api.rpc.chain.getBlockHash(7487667);
	const block7487667 = await api.rpc.chain.getBlock(blockHash7487667);`

**Comment by vae520283995** [comment]
2021-05-15 23:52:27             VEC: Unable to decode on index 2 createType(ExtrinsicV4):: createType(Call):: Call: failed decoding electionProviderMultiPhase.submitUnsigned:: Struct: failed on args: {"solution":"RawSolution","witness":"SolutionOrSnapshotSize"}:: u32: Input too large. Found input with 77 bits, expected 32
2021-05-15 23:52:27        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding electionProviderMultiPhase.submitUnsigned:: Struct: failed on args: {"solution":"RawSolution","witness":"SolutionOrSnapshotSize"}:: u32: Input too large. Found input with 77 bits, expected 32
Error: createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding electionProviderMultiPhase.submitUnsigned:: Struct: failed on args: {"solution":"RawSolution","witness":"SolutionOrSnapshotSize"}:: u32: Input too large. Found input with 77 bits, expected 32
    at createTypeUnsafe (/Users/zeke/Documents/parity/tools-sandbox/node_modules/@polkadot/types/create/createType.cjs:55:11)
    at RpcCore._formatOutput (/Users/zeke/Documents/parity/tools-sandbox/node_modules/@polkadot/rpc-core/index.cjs:381:41)
    at callWithRegistry (/Users/zeke/Documents/parity/tools-sandbox/node_modules/@polkadot/rpc-core/index.cjs:247:42)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)

**Comment by vae520283995** [comment]
- SAS:
  📦 LOG:
     ✅ LEVEL: "info"
     ✅ JSON: false
     ✅ FILTER_RPC: false
     ✅ STRIP_ANSI: false
  📦 SUBSTRATE:
     ✅ WS_URL: "ws://172.31.26.63:19966"
     ✅ TYPES_BUNDLE: undefined
     ✅ TYPES_CHAIN: undefined
     ✅ TYPES_SPEC: undefined
     ✅ TYPES: undefined
  📦 EXPRESS:
     ✅ BIND_HOST: "0.0.0.0"
     ✅ PORT: 8080
2021-05-16 04:07:59 info: Version: 6.0.0
2021-05-16 04:08:01 info: Connected to chain Kusama on the parity-kusama client at ws://172.31.26.63:19966
2021-05-16 04:08:01 warn: Using unencrypted connection to a public node (ws://172.31.26.63:19966); All traffic is sent over the internet in cleartext.
2021-05-16 04:08:01 info: Listening on http://0.0.0.0:8080/
2021-05-16 04:08:01 info: Check the root endpoint (http://0.0.0.0:8080/) to see the available endpoints for the current node
2021-05-16 04:08:04 error: VEC: Unable to decode on index 2 createType(ExtrinsicV4):: createType(Call):: Call: failed decoding electionProviderMultiPhase.submitUnsigned:: Struct: failed on args: {"solution":"RawSolution","witness":"SolutionOrSnapshotSize"}:: u32: Input too large. Found input with 77 bits, expected 32
2021-05-16 04:08:04 error: RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: Call: failed decoding electionProviderMultiPhase.submitUnsigned:: Struct: failed on args: {"solution":"RawSolution","witness":"SolutionOrSnapshotSize"}:: u32: Input too large. Found input with 77 bits, expected 32

-
